paperless_stack_dir: /opt/paperless-stack
paperless_tz: America/Phoenix

paperless_port: 8000
paperless_ai_port: 3000
open_webui_port: 3001
paperless_gpt_port: 3002
dozzle_port: 8080

paperless_enable_ai: false
paperless_enable_dozzle: true
paperless_enable_nvidia: false

paperless_db_name: paperless
paperless_db_user: paperless

ollama_text_model: "llama3.2:3b"
ollama_vision_model: "minicpm-v:8b"
